package com.miferstlab.binauralbeats.ui

// GENERATED by tools/gen_ambient_kotlin.py — do not edit by hand.

import androidx.annotation.StringRes
import com.miferstlab.binauralbeats.R
import com.miferstlab.binauralbeats.data.AmbientCategory
import com.miferstlab.binauralbeats.data.AmbientSound

@StringRes
fun ambientLabelRes(ambient: AmbientSound): Int = when (ambient) {
    AmbientSound.OFF -> R.string.ambient_off
    AmbientSound.NATURE_RAIN -> R.string.ambient_nature_rain
    AmbientSound.NATURE_THUNDER -> R.string.ambient_nature_thunder
    AmbientSound.NATURE_WAVES -> R.string.ambient_nature_waves
    AmbientSound.NATURE_STREAM -> R.string.ambient_nature_stream
    AmbientSound.NATURE_FIREPLACE -> R.string.ambient_nature_fireplace
    AmbientSound.NATURE_NIGHT_FOREST -> R.string.ambient_nature_night_forest
    AmbientSound.NATURE_CAVE -> R.string.ambient_nature_cave
    AmbientSound.JOYFUL_DAWN_CHORUS -> R.string.ambient_joyful_dawn_chorus
    AmbientSound.JOYFUL_SUNNY_MEADOW -> R.string.ambient_joyful_sunny_meadow
    AmbientSound.JOYFUL_SUMMER_FIELD -> R.string.ambient_joyful_summer_field
    AmbientSound.JOYFUL_STREET_MARKET -> R.string.ambient_joyful_street_market
    AmbientSound.CALM_GENTLE_WAVES -> R.string.ambient_calm_gentle_waves
    AmbientSound.CALM_BROOK -> R.string.ambient_calm_brook
    AmbientSound.CALM_PROVENCE_DUSK -> R.string.ambient_calm_provence_dusk
    AmbientSound.CALM_NIGHT_BREEZE -> R.string.ambient_calm_night_breeze
    AmbientSound.FOCUS_CAFE -> R.string.ambient_focus_cafe
    AmbientSound.FOCUS_LIBRARY -> R.string.ambient_focus_library
    AmbientSound.FOCUS_WATERFALL -> R.string.ambient_focus_waterfall
    AmbientSound.FOCUS_CABIN_RAIN -> R.string.ambient_focus_cabin_rain
    AmbientSound.SLEEP_STEADY_RAIN -> R.string.ambient_sleep_steady_rain
    AmbientSound.SLEEP_RAIN_WINDOW -> R.string.ambient_sleep_rain_window
    AmbientSound.SLEEP_DESERT_WIND -> R.string.ambient_sleep_desert_wind
    AmbientSound.SLEEP_NIGHT_STORM -> R.string.ambient_sleep_night_storm
    AmbientSound.SLEEP_WINTER_STORM -> R.string.ambient_sleep_winter_storm
    AmbientSound.MEL_GREY_MORNING -> R.string.ambient_mel_grey_morning
    AmbientSound.MEL_AUTUMN_LEAVES -> R.string.ambient_mel_autumn_leaves
    AmbientSound.MEL_FROZEN_NIGHT -> R.string.ambient_mel_frozen_night
    AmbientSound.MEL_DISTANT_CHIMES -> R.string.ambient_mel_distant_chimes
    AmbientSound.NOIR_RAINY_CROSSROAD -> R.string.ambient_noir_rainy_crossroad
    AmbientSound.NOIR_WET_STREET -> R.string.ambient_noir_wet_street
    AmbientSound.NOIR_OLD_CLOCK -> R.string.ambient_noir_old_clock
    AmbientSound.NOIR_RAIN_WINDOW -> R.string.ambient_noir_rain_window
    AmbientSound.NOIR_DOWNTOWN_STORM -> R.string.ambient_noir_downtown_storm
    AmbientSound.FANTASY_TAVERN -> R.string.ambient_fantasy_tavern
    AmbientSound.FANTASY_VILLAGE -> R.string.ambient_fantasy_village
    AmbientSound.FANTASY_BELLS -> R.string.ambient_fantasy_bells
    AmbientSound.FANTASY_DRIPPING_CAVE -> R.string.ambient_fantasy_dripping_cave
    AmbientSound.FANTASY_PEAK_WIND -> R.string.ambient_fantasy_peak_wind
    AmbientSound.FANTASY_OLD_FOREST -> R.string.ambient_fantasy_old_forest
    AmbientSound.SCIFI_SHIP_HUM -> R.string.ambient_scifi_ship_hum
    AmbientSound.SCIFI_STARSHIP -> R.string.ambient_scifi_starship
    AmbientSound.SCIFI_ENGINEERING -> R.string.ambient_scifi_engineering
    AmbientSound.SCIFI_STATION -> R.string.ambient_scifi_station
    AmbientSound.SCIFI_NIGHT_CITY -> R.string.ambient_scifi_night_city
}

@StringRes
fun ambientCategoryRes(category: AmbientCategory): Int = when (category) {
    AmbientCategory.NATURE -> R.string.ambient_cat_nature
    AmbientCategory.JOYFUL -> R.string.ambient_cat_joyful
    AmbientCategory.CALM -> R.string.ambient_cat_calm
    AmbientCategory.FOCUS -> R.string.ambient_cat_focus
    AmbientCategory.SLEEP -> R.string.ambient_cat_sleep
    AmbientCategory.MELANCHOLIC -> R.string.ambient_cat_melancholic
    AmbientCategory.NOIR -> R.string.ambient_cat_noir
    AmbientCategory.FANTASY -> R.string.ambient_cat_fantasy
    AmbientCategory.SCI_FI -> R.string.ambient_cat_scifi
}
