#!/usr/bin/env python3
"""Generate AmbientSound.kt, AmbientText.kt and the ambient block of values/strings.xml
from tools/ambient_tracks.json. Run after editing the spec."""
import json, re
from pathlib import Path
from xml.sax.saxutils import escape

ROOT = Path(__file__).resolve().parents[1]
spec = json.loads((ROOT / "tools/ambient_tracks.json").read_text())
PKG = ROOT / "app/src/main/java/com/miferstlab/binauralbeats"
CATS = {"nature": ("NATURE", "Nature"), "joyful": ("JOYFUL", "Joyful"), "calm": ("CALM", "Calm"),
        "focus": ("FOCUS", "Focus"), "sleep": ("SLEEP", "Sleep"), "melancholic": ("MELANCHOLIC", "Melancholic"),
        "noir": ("NOIR", "Crime & Noir"), "fantasy": ("FANTASY", "Fantasy"), "scifi": ("SCI_FI", "Sci‑Fi")}
# Old prefs values (≤ v1.4.x) → new keys, so upgraded users keep a sensible selection.
LEGACY = {"forest_night": "nature_night_forest", "waves": "nature_waves", "morning_village": "joyful_dawn_chorus",
          "rain": "nature_rain", "fireplace": "nature_fireplace", "stream": "nature_stream",
          "mountain_wind": "fantasy_peak_wind", "cave_drip": "nature_cave", "soft_thunder": "nature_thunder"}

def kstr(s): return json.dumps(s, ensure_ascii=False).replace("$", "\\$")
def enum_name(key): return key.upper()

cat_lines = ",\n".join(f'    {CATS[c][0]}("{c}")' for c in spec["categories"])
tr = []
for t in spec["tracks"]:
    tr.append(f'    {enum_name(t["key"])}(\n        "{t["key"]}", AmbientCategory.{CATS[t["cat"]][0]},\n'
              f'        sourceTitle = {kstr(t["source_title"])}, author = {kstr(t["author"])},\n'
              f'        sourceUrl = {kstr(t["url"])}, license = {kstr(t["license"])}\n    )')
legacy = ",\n".join(f'            "{k}" to {enum_name(v)}' for k, v in LEGACY.items())
(PKG / "data/AmbientSound.kt").write_text(f'''package com.miferstlab.binauralbeats.data

// GENERATED by tools/gen_ambient_kotlin.py from tools/ambient_tracks.json — do not edit by hand.

/** Mood / use-case groups shown as tabs in the ambient picker. */
enum class AmbientCategory(val prefsValue: String) {{
{cat_lines}
}}

/**
 * Looping ambient beds layered under binaural tones. Audio lives in
 * `assets/ambient/<prefsValue>.ogg` (≈5 min, -20 LUFS, seamless crossfaded loop).
 * All sources are Freesound CC0 recordings; credits are shown in Settings → Sound credits.
 *
 * There is no per-track tier: every bed is available whenever the app is usable
 * (7-day trial or Premium) — the only gate is the app-wide trial/purchase check.
 */
enum class AmbientSound(
    val prefsValue: String,
    val category: AmbientCategory?,
    val sourceTitle: String = "",
    val author: String = "",
    val sourceUrl: String = "",
    val license: String = ""
) {{
    OFF("off", null),
{",\n".join(tr)};

    /** Path inside the APK assets, or null for [OFF]. */
    val assetPath: String? get() = if (this == OFF) null else "ambient/$prefsValue.ogg"

    companion object {{
        private val legacy: Map<String, AmbientSound> = mapOf(
{legacy}
        )

        fun fromPrefs(value: String?): AmbientSound =
            entries.firstOrNull {{ it.prefsValue == value }} ?: legacy[value] ?: OFF

        fun inCategory(category: AmbientCategory): List<AmbientSound> =
            entries.filter {{ it.category == category }}

        val tracks: List<AmbientSound> = entries.filter {{ it != OFF }}
    }}
}}
''')

lab = "\n".join(f'    AmbientSound.{enum_name(t["key"])} -> R.string.ambient_{t["key"]}' for t in spec["tracks"])
catm = "\n".join(f'    AmbientCategory.{CATS[c][0]} -> R.string.ambient_cat_{c}' for c in spec["categories"])
(PKG / "ui/AmbientText.kt").write_text(f'''package com.miferstlab.binauralbeats.ui

// GENERATED by tools/gen_ambient_kotlin.py — do not edit by hand.

import androidx.annotation.StringRes
import com.miferstlab.binauralbeats.R
import com.miferstlab.binauralbeats.data.AmbientCategory
import com.miferstlab.binauralbeats.data.AmbientSound

@StringRes
fun ambientLabelRes(ambient: AmbientSound): Int = when (ambient) {{
    AmbientSound.OFF -> R.string.ambient_off
{lab}
}}

@StringRes
fun ambientCategoryRes(category: AmbientCategory): Int = when (category) {{
{catm}
}}
''')

block = ["    <!-- BEGIN GENERATED AMBIENT (tools/gen_ambient_kotlin.py) -->"]
block += [f'    <string name="ambient_cat_{c}">{escape(CATS[c][1])}</string>' for c in spec["categories"]]
block += [f'    <string name="ambient_{t["key"]}">{escape(t["name"]).replace(chr(39), chr(92)+chr(39))}</string>' for t in spec["tracks"]]
block += ["    <!-- END GENERATED AMBIENT -->"]
sx = ROOT / "app/src/main/res/values/strings.xml"
s = sx.read_text()
s = re.sub(r"    <!-- BEGIN GENERATED AMBIENT.*?END GENERATED AMBIENT -->", "\n".join(block), s, flags=re.S) \
    if "BEGIN GENERATED AMBIENT" in s else s.replace("</resources>", "\n".join(block) + "\n</resources>")
sx.write_text(s)
print("generated", len(spec["tracks"]), "tracks")
